### ISSUE TITLE
Error: Invalid IV length on decrypt

### ISSUE THREAD

**Issue by sjungwirth** [TomFrost/Cryptex#11]
following the guide I:
- created a KMS key
- used aws-cli to create a data-key
- encrypted secrets `cryptex encrypt secret`
- added secret blob to cryptex.json
- attempt to decrypt secret blob

```
$ cryptex decrypt mysecret
Uh-oh, we have a problem:
Error: Invalid IV length
    at Error (native)
    at new Decipheriv (crypto.js:242:16)
    at Object.Decipheriv (crypto.js:239:12)
    at AES256.decrypt (/Users/scott/code/crypt-test/node_modules/cryptex/src/lib/SymmetricAlgo.js:22:29)
    at Promise.resolve.then.then (/Users/scott/code/crypt-test/node_modules/cryptex/src/index.js:51:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Same error on Node 8 and Node 6.

Maybe my KMS key isn't set up right, not sure, any help would be appreciated though.

**Comment by TomFrost** [comment]
Hey Scott! I’m so sorry, that’s a typo in the guide you read that I can no longer fix. Replace `decrypt` in that final command with `getSecret` and you’re all set. The decrypt command is actually for decrypting data passed in on the command line, rather than decrypting stored secrets.

**Comment by sjungwirth** [comment]
That works! Thanks a lot. I guess I should have looked more carefully at the README. Thanks again for the quick response!

**Comment by TomFrost** [comment]
Not your fault at all! Enjoy the lib :)
